layout_spectrum: 0.57814
favicon: null
name: davidspriggs
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
  brandColors:
    - '#161517'
    - '#706C6E'
    - '#3A3839'
    - '#E9DED9'
typography_spectrum: 0.47489
