name: davidspriggs
favicon: null
layout_spectrum: 0.25774
typography_spectrum: 0.39867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181a19'
    - '#313131'
    - '#4b4c46'
    - '#6f6d60'
    - '#8d8b7e'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
